### ISSUE TITLE
List Config disappears

### ISSUE THREAD

**Issue by ThomasBrelinski** [microsoft/azure-devops-extension-cascading-picklist#29] opened 2019-10-24 18:12 UTC
I saved my configuration in my Azure DevOps Project.  Tested it.  It works wonderfully.  Then, two days later configuration reverted to the default config.  Not sure what is happening or what I am not doing.  Please help.  I save a backup now to quickly replace.  This has happened twice.

**Comment by mundafDS** [comment] 2019-10-28 18:51
This happens to me as well.  I've also had several others in our organization test it and every single time someone logs in from their phone, it's set back to default config.  This is something that we really love and need to use, but being the person who has to write the JSON... you get it.  You know you get it.

**Comment by jnhaffey** [comment] 2019-11-02 11:17
I am also having this same issue and have to fix this 3 times now.  I am unsure of the root cause but I know that I spent a lot of time setting up the configuration only to have it 'stop working' days later and find that the configuration has been reset back to its default value.

Please find a fix for this and sort it as this is becoming extremely annoying.

**Comment by prashanthbv12** [comment] 2019-12-02 11:31
Is this fixed then? How can update this new change to Azure devops.

**Comment by ThomasBrelinski** [comment] 2019-12-11 20:56
Is this resolved?  If so do I need to remove and install this extension again?  Looking for help to fix this issue.

**Comment by prashanthbv12** [comment] 2020-01-14 12:01
Is This fixed?

**Comment by ThomasBrelinski** [comment] 2020-01-14 19:21
I have had to rebuild my config once this week.  Is there something I need to do?

**Comment by vadim-kovalyov** [comment] 2020-01-22 21:23
We've just merged #34 and published a new version of the extension. Please give it a try and let us know if you can still repro the issue.

**Closed** 2020-01-22 22:07 UTC

**Comment by ThomasBrelinski** [comment] 2020-01-31 01:02
I just uninstalled it from our Azure DevOps organization.  Then wen to the marketplace and installed it again.  Is that what I needed to do?
